/*
  This file is automatically generated. Any changes will be overwritten.
  Modify kurse.component.ts instead.
*/
import { LOCALE_ID, ChangeDetectorRef, ViewChild, AfterViewInit, Injector, OnInit, OnDestroy } from '@angular/core';
import { Router, ActivatedRoute } from '@angular/router';
import { Location } from '@angular/common';
import { HttpClient, HttpParams, HttpHeaders } from '@angular/common/http';
import { Subscription } from 'rxjs';

import { DialogService, DIALOG_PARAMETERS, DialogRef } from '@radzen/angular/dist/dialog';
import { NotificationService } from '@radzen/angular/dist/notification';
import { ContentComponent } from '@radzen/angular/dist/content';
import { HeadingComponent } from '@radzen/angular/dist/heading';
import { TabsComponent } from '@radzen/angular/dist/tabs';
import { PanelComponent } from '@radzen/angular/dist/panel';
import { GridComponent } from '@radzen/angular/dist/grid';
import { ButtonComponent } from '@radzen/angular/dist/button';

import { ConfigService } from '../config.service';
import { MeldungLoeschenComponent } from '../meldung-loeschen/meldung-loeschen.component';
import { KurseThemenBearbeitenComponent } from '../kurse-themen-bearbeiten/kurse-themen-bearbeiten.component';
import { KurseThemenNeuComponent } from '../kurse-themen-neu/kurse-themen-neu.component';
import { KurseBearbeitenComponent } from '../kurse-bearbeiten/kurse-bearbeiten.component';
import { KurseNeuComponent } from '../kurse-neu/kurse-neu.component';

import { DbHopeKurseTextbausteineService } from '../db-hope-kurse-textbausteine.service';
import { SecurityService } from '../security.service';

export class KurseGenerated implements AfterViewInit, OnInit, OnDestroy {
  // Components
  @ViewChild('content1') content1: ContentComponent;
  @ViewChild('heading8') heading8: HeadingComponent;
  @ViewChild('heading9') heading9: HeadingComponent;
  @ViewChild('heading2') heading2: HeadingComponent;
  @ViewChild('tabs0') tabs0: TabsComponent;
  @ViewChild('panel0') panel0: PanelComponent;
  @ViewChild('gridKurse') gridKurse: GridComponent;
  @ViewChild('buttonNeu') buttonNeu: ButtonComponent;
  @ViewChild('buttonBearbeiten') buttonBearbeiten: ButtonComponent;
  @ViewChild('buttonLoeschen') buttonLoeschen: ButtonComponent;
  @ViewChild('panel1') panel1: PanelComponent;
  @ViewChild('gridKurseThemenListe') gridKurseThemenListe: GridComponent;
  @ViewChild('panel2') panel2: PanelComponent;
  @ViewChild('gridKurseThemen') gridKurseThemen: GridComponent;
  @ViewChild('button0') button0: ButtonComponent;
  @ViewChild('button1') button1: ButtonComponent;
  @ViewChild('button2') button2: ButtonComponent;

  router: Router;

  cd: ChangeDetectorRef;

  route: ActivatedRoute;

  notificationService: NotificationService;

  configService: ConfigService;

  dialogService: DialogService;

  dialogRef: DialogRef;

  httpClient: HttpClient;

  locale: string;

  _location: Location;

  _subscription: Subscription;

  dbHopeKurseTextbausteine: DbHopeKurseTextbausteineService;

  security: SecurityService;
  letzteKursNr: any;
  letzteKursThemaNr: any;
  parameters: any;
  rstKurse: any;
  rstKurseCount: any;
  dsoKurse: any;
  rstKurseThemen: any;
   rstKurseThemenCount: any;
  dsoKurseThemen: any;

  constructor(private injector: Injector) {
  }

  ngOnInit() {
    this.notificationService = this.injector.get(NotificationService);

    this.configService = this.injector.get(ConfigService);

    this.dialogService = this.injector.get(DialogService);

    this.dialogRef = this.injector.get(DialogRef, null);

    this.locale = this.injector.get(LOCALE_ID);

    this.router = this.injector.get(Router);

    this.cd = this.injector.get(ChangeDetectorRef);

    this._location = this.injector.get(Location);

    this.route = this.injector.get(ActivatedRoute);

    this.httpClient = this.injector.get(HttpClient);

    this.dbHopeKurseTextbausteine = this.injector.get(DbHopeKurseTextbausteineService);
    this.security = this.injector.get(SecurityService);
  }

  ngAfterViewInit() {
    this._subscription = this.route.params.subscribe(parameters => {
      if (this.dialogRef) {
        this.parameters = this.injector.get(DIALOG_PARAMETERS);
      } else {
        this.parameters = parameters;
      }
      this.load();
      this.cd.detectChanges();
    });
  }

  ngOnDestroy() {
    if (this._subscription) {
      this._subscription.unsubscribe();
    }
  }


  load() {
    this.letzteKursNr = null;

    this.letzteKursThemaNr = null;

    this.gridKurse.load();
  }

  gridKurseLoadData(event: any) {
    this.dbHopeKurseTextbausteine.getIbsiKurses(`${event.filter} and Titel ne '(Online-Registrierung)' and Titel ne '(Datenübernahme FileMaker)'`, event.top, event.skip, `${event.orderby || 'Titel'}`, event.top != null && event.skip != null, `IbsiKurseArten`, null, null)
    .subscribe((result: any) => {
      this.rstKurse = result.value;

      this.rstKurseCount = event.top != null && event.skip != null ? result['@odata.count'] : result.value.length;

      if (this.rstKurse.find(p => p.KursNr == this.letzteKursNr) != null) {
    // letzteKursNr wurde in rstKurse gefunden
    this.gridKurse.onSelect(this.rstKurse.find(p => p.KursNr == this.letzteKursNr));
} else {
    // letzteKursNr wurde in rstKursNr NICHT gefunden
    this.letzteKursNr = null;
    this.gridKurse.onSelect(this.rstKurse[0]);
}
    }, (result: any) => {
      this.notificationService.notify({ severity: "error", summary: ``, detail: `Kurse können nicht geladen werden!` });
    });
  }

  gridKurseRowDoubleClick(event: any) {
    this.letzteKursNr = this.dsoKurse.KursNr;

    this.dialogService.open(KurseBearbeitenComponent, { parameters: {KursNr: event.KursNr}, title: `Bearbeiten Kurs` });
  }

  gridKurseRowSelect(event: any) {
    this.dsoKurse = event;

    this.gridKurseThemen.load();
  }

  buttonNeuClick(event: any) {
    this.letzteKursNr = this.dsoKurse.KursNr;

    this.dialogService.open(KurseNeuComponent, { parameters: {}, title: `Neuer Kurs` })
        .afterClosed().subscribe(result => {
              if (result != null) {
            this.letzteKursNr = result.KursNr;
      }

      if (result != null) {
        this.gridKurse.load();
      }
    });
  }

  buttonBearbeitenClick(event: any) {
    this.letzteKursNr = this.dsoKurse.KursNr;

    this.dialogService.open(KurseBearbeitenComponent, { parameters: {KursNr: this.dsoKurse.KursNr}, title: `Bearbeiten Kurs` });
  }

  buttonLoeschenClick(event: any) {
    this.letzteKursNr = null;

    this.dialogService.open(MeldungLoeschenComponent, { parameters: {strMeldung: "Soll der Kurs '" + this.dsoKurse.Titel + "' gelöscht werden?"}, title: `Löschen Kurs` })
        .afterClosed().subscribe(result => {
              if (result == 'Löschen') {
              this.dbHopeKurseTextbausteine.deleteIbsiKurse(this.dsoKurse.KursNr)
        .subscribe((result: any) => {
              this.notificationService.notify({ severity: "success", summary: ``, detail: `Kurs gelöscht` });
        }, (result: any) => {
              this.notificationService.notify({ severity: "error", summary: ``, detail: `Kurs konnte nicht gelöscht werden!` });
        });
      }
    });
  }

  gridKurseThemenLoadData(event: any) {
    this.dbHopeKurseTextbausteine.getIbsiKurseThemens(`KursNr eq ${this.dsoKurse.KursNr}`, event.top, event.skip, `${event.orderby || 'Nummer'}`, event.top != null && event.skip != null, null, null, null)
    .subscribe((result: any) => {
      this.rstKurseThemen = result.value;

      this. rstKurseThemenCount = event.top != null && event.skip != null ? result['@odata.count'] : result.value.length;

      if (this.rstKurseThemen.find(p => p.KursThemaNr == this.letzteKursThemaNr) != null) {
    // letzteKursThemaNr wurde in rstKurseThemen gefunden
    this.gridKurseThemen.onSelect(this.rstKurseThemen.find(p => p.KursThemaNr == this.letzteKursThemaNr))
} else {
    // letzteKursThemaNr wurde in rstKursThemaNr NICHT gefunden
    this.letzteKursThemaNr = null;
    this.gridKurseThemen.onSelect(this.rstKurseThemen[0]);
}
    }, (result: any) => {

    });
  }

  gridKurseThemenRowDoubleClick(event: any) {
    this.letzteKursThemaNr = this.dsoKurseThemen.KursThemaNr;

    this.dialogService.open(KurseThemenBearbeitenComponent, { parameters: {KursThemaNr: event.KursThemaNr}, title: 'KurseThemenBearbeiten' });
  }

  gridKurseThemenRowSelect(event: any) {
    this.dsoKurseThemen = event;

    this.letzteKursThemaNr = event.KursThemaNr;
  }

  button0Click(event: any) {
    this.letzteKursThemaNr = this.dsoKurseThemen.KursThemaNr;

    this.dialogService.open(KurseThemenNeuComponent, { parameters: {}, title: `Neues Thema` })
        .afterClosed().subscribe(result => {
              if (result != null) {
            this.letzteKursThemaNr = result.KursThemaNr;
      }

      if (result != null) {
        this.gridKurseThemen.load();
      }
    });
  }

  button1Click(event: any) {
    this.letzteKursThemaNr = this.dsoKurseThemen.KursThemaNr;

    this.dialogService.open(KurseThemenBearbeitenComponent, { parameters: {KursThemaNr: this.dsoKurseThemen.KursThemaNr}, title: `Bearbeiten Thema` });
  }

  button2Click(event: any) {
    this.letzteKursThemaNr = null;

    this.dialogService.open(MeldungLoeschenComponent, { parameters: {strMeldung: "Soll das Thema '" + this.dsoKurseThemen.Titel + "' gelöscht werden?"}, title: `Löschen Thema` })
        .afterClosed().subscribe(result => {
              if (result == 'Löschen') {
              this.dbHopeKurseTextbausteine.deleteIbsiKurseThemen(this.dsoKurseThemen.KursThemaNr)
        .subscribe((result: any) => {
              this.notificationService.notify({ severity: "success", summary: ``, detail: `Thema gelöscht` });
        }, (result: any) => {
              this.notificationService.notify({ severity: "error", summary: ``, detail: `Thema konnte nicht gelöscht werden!` });
        });
      }
    });
  }
}
