/*
  This file is automatically generated. Any changes will be overwritten.
  Modify copy-of-kontakte-1.component.ts instead.
*/
import { LOCALE_ID, ChangeDetectorRef, ViewChild, AfterViewInit, Injector, OnInit, OnDestroy } from '@angular/core';
import { Router, ActivatedRoute } from '@angular/router';
import { Location } from '@angular/common';
import { HttpClient, HttpParams, HttpHeaders } from '@angular/common/http';
import { Subscription } from 'rxjs';

import { DialogService, DIALOG_PARAMETERS, DialogRef } from '@radzen/angular/dist/dialog';
import { NotificationService } from '@radzen/angular/dist/notification';
import { ContentComponent } from '@radzen/angular/dist/content';
import { HeadingComponent } from '@radzen/angular/dist/heading';
import { TabsComponent } from '@radzen/angular/dist/tabs';
import { GridComponent } from '@radzen/angular/dist/grid';
import { PanelComponent } from '@radzen/angular/dist/panel';
import { TemplateFormComponent } from '@radzen/angular/dist/template-form';
import { LabelComponent } from '@radzen/angular/dist/label';
import { DropDownComponent } from '@radzen/angular/dist/dropdown';
import { TextBoxComponent } from '@radzen/angular/dist/textbox';
import { RequiredValidatorComponent } from '@radzen/angular/dist/required-validator';
import { DatePickerComponent } from '@radzen/angular/dist/datepicker';
import { TextAreaComponent } from '@radzen/angular/dist/textarea';
import { ButtonComponent } from '@radzen/angular/dist/button';

import { ConfigService } from '../config.service';

import { DbHopeKurseTextbausteineService } from '../db-hope-kurse-textbausteine.service';
import { SecurityService } from '../security.service';

export class CopyOfKontakte1Generated implements AfterViewInit, OnInit, OnDestroy {
  // Components
  @ViewChild('content1') content1: ContentComponent;
  @ViewChild('heading8') heading8: HeadingComponent;
  @ViewChild('heading9') heading9: HeadingComponent;
  @ViewChild('heading16') heading16: HeadingComponent;
  @ViewChild('heading1') heading1: HeadingComponent;
  @ViewChild('heading4') heading4: HeadingComponent;
  @ViewChild('heading0') heading0: HeadingComponent;
  @ViewChild('heading2') heading2: HeadingComponent;
  @ViewChild('tabs0') tabs0: TabsComponent;
  @ViewChild('gridKontakte') gridKontakte: GridComponent;
  @ViewChild('panel2') panel2: PanelComponent;
  @ViewChild('templateForm0') templateForm0: TemplateFormComponent;
  @ViewChild('label7') label7: LabelComponent;
  @ViewChild('dropdown0') dropdown0: DropDownComponent;
  @ViewChild('label8') label8: LabelComponent;
  @ViewChild('textboxName') textboxName: TextBoxComponent;
  @ViewChild('requiredValidator0') requiredValidator0: RequiredValidatorComponent;
  @ViewChild('label18') label18: LabelComponent;
  @ViewChild('textboxVorname') textboxVorname: TextBoxComponent;
  @ViewChild('requiredValidator2') requiredValidator2: RequiredValidatorComponent;
  @ViewChild('label9') label9: LabelComponent;
  @ViewChild('textboxKurzel') textboxKurzel: TextBoxComponent;
  @ViewChild('requiredValidator1') requiredValidator1: RequiredValidatorComponent;
  @ViewChild('label10') label10: LabelComponent;
  @ViewChild('textbox4') textbox4: TextBoxComponent;
  @ViewChild('textbox5') textbox5: TextBoxComponent;
  @ViewChild('label11') label11: LabelComponent;
  @ViewChild('textbox6') textbox6: TextBoxComponent;
  @ViewChild('label12') label12: LabelComponent;
  @ViewChild('textbox7') textbox7: TextBoxComponent;
  @ViewChild('textbox8') textbox8: TextBoxComponent;
  @ViewChild('label13') label13: LabelComponent;
  @ViewChild('textbox9') textbox9: TextBoxComponent;
  @ViewChild('label14') label14: LabelComponent;
  @ViewChild('textbox10') textbox10: TextBoxComponent;
  @ViewChild('label15') label15: LabelComponent;
  @ViewChild('textbox11') textbox11: TextBoxComponent;
  @ViewChild('label16') label16: LabelComponent;
  @ViewChild('textbox12') textbox12: TextBoxComponent;
  @ViewChild('label17') label17: LabelComponent;
  @ViewChild('datepicker0') datepicker0: DatePickerComponent;
  @ViewChild('label19') label19: LabelComponent;
  @ViewChild('textarea1') textarea1: TextAreaComponent;
  @ViewChild('button4') button4: ButtonComponent;

  router: Router;

  cd: ChangeDetectorRef;

  route: ActivatedRoute;

  notificationService: NotificationService;

  configService: ConfigService;

  dialogService: DialogService;

  dialogRef: DialogRef;

  httpClient: HttpClient;

  locale: string;

  _location: Location;

  _subscription: Subscription;

  dbHopeKurseTextbausteine: DbHopeKurseTextbausteineService;

  security: SecurityService;
  rstBaseAnreden: any;
  parameters: any;
  rstBaseAlles: any;
  rstBaseAllesCount: any;
  dataBaseAlles: any;
  zeileAusgewaehlt: any;

  constructor(private injector: Injector) {
  }

  ngOnInit() {
    this.notificationService = this.injector.get(NotificationService);

    this.configService = this.injector.get(ConfigService);

    this.dialogService = this.injector.get(DialogService);

    this.dialogRef = this.injector.get(DialogRef, null);

    this.locale = this.injector.get(LOCALE_ID);

    this.router = this.injector.get(Router);

    this.cd = this.injector.get(ChangeDetectorRef);

    this._location = this.injector.get(Location);

    this.route = this.injector.get(ActivatedRoute);

    this.httpClient = this.injector.get(HttpClient);

    this.dbHopeKurseTextbausteine = this.injector.get(DbHopeKurseTextbausteineService);
    this.security = this.injector.get(SecurityService);
  }

  ngAfterViewInit() {
    this._subscription = this.route.params.subscribe(parameters => {
      if (this.dialogRef) {
        this.parameters = this.injector.get(DIALOG_PARAMETERS);
      } else {
        this.parameters = parameters;
      }
      this.load();
      this.cd.detectChanges();
    });
  }

  ngOnDestroy() {
    if (this._subscription) {
      this._subscription.unsubscribe();
    }
  }


  load() {
    this.dbHopeKurseTextbausteine.getBaseAnredens(null, null, null, null, null, null, null, null)
    .subscribe((result: any) => {
      this.rstBaseAnreden = result.value;
    }, (result: any) => {

    });

    this.gridKontakte.load();
  }

  gridKontakteDelete(event: any) {
    this.dbHopeKurseTextbausteine.deleteBase(event.BaseID)
    .subscribe((result: any) => {
      this.notificationService.notify({ severity: "success", summary: `Success`, detail: `Kontakt gelöscht` });
    }, (result: any) => {
      this.notificationService.notify({ severity: "error", summary: `Error`, detail: `Kontakt kann nicht gelöscht werden` });
    });
  }

  gridKontakteLoadData(event: any) {
    this.dbHopeKurseTextbausteine.getVwBaseAlles(`${event.filter}`, event.top, event.skip, `${event.orderby || 'Name1, Name2'}`, event.top != null && event.skip != null, null, null, null)
    .subscribe((result: any) => {
      this.rstBaseAlles = result.value;

      this.rstBaseAllesCount = event.top != null && event.skip != null ? result['@odata.count'] : result.value.length;

      this.gridKontakte.onSelect(result.value[0])
    }, (result: any) => {
      this.notificationService.notify({ severity: "error", summary: `Error`, detail: `Kontakte können nicht geladen werden` });
    });
  }

  gridKontakteRowSelect(event: any) {
    this.dataBaseAlles = event;

    this.zeileAusgewaehlt = ((this.gridKontakte.dataTable.anchorRowIndex === null || this.gridKontakte.dataTable.anchorRowIndex === undefined) ? 0 : this.gridKontakte.dataTable.anchorRowIndex) + 1;
  }

  templateForm0Submit(event: any) {
    this.dbHopeKurseTextbausteine.updateBase(null, this.dataBaseAlles.BaseID, event)
    .subscribe((result: any) => {
      this.notificationService.notify({ severity: "success", summary: `Success`, detail: `Kontakt gespeichert` });

      this.gridKontakte.load()
    }, (result: any) => {
      this.notificationService.notify({ severity: "error", summary: `Error`, detail: `Kontakt konnte nicht gespeichert werden` });
    });
  }
}
