/*
  This file is automatically generated. Any changes will be overwritten.
  Modify kontakte-v-1.component.ts instead.
*/
import { LOCALE_ID, ChangeDetectorRef, ViewChild, AfterViewInit, Injector, OnInit, OnDestroy } from '@angular/core';
import { Router, ActivatedRoute } from '@angular/router';
import { Location } from '@angular/common';
import { HttpClient, HttpParams, HttpHeaders } from '@angular/common/http';
import { Subscription } from 'rxjs';

import { DialogService, DIALOG_PARAMETERS, DialogRef } from '@radzen/angular/dist/dialog';
import { NotificationService } from '@radzen/angular/dist/notification';
import { ContentComponent } from '@radzen/angular/dist/content';
import { HeadingComponent } from '@radzen/angular/dist/heading';
import { TabsComponent } from '@radzen/angular/dist/tabs';
import { GridComponent } from '@radzen/angular/dist/grid';
import { PanelComponent } from '@radzen/angular/dist/panel';
import { TemplateFormComponent } from '@radzen/angular/dist/template-form';
import { LabelComponent } from '@radzen/angular/dist/label';
import { DropDownComponent } from '@radzen/angular/dist/dropdown';
import { RequiredValidatorComponent } from '@radzen/angular/dist/required-validator';
import { TextBoxComponent } from '@radzen/angular/dist/textbox';
import { TextAreaComponent } from '@radzen/angular/dist/textarea';
import { ButtonComponent } from '@radzen/angular/dist/button';

import { ConfigService } from '../config.service';
import { KontakteNeuComponent } from '../kontakte-neu/kontakte-neu.component';

import { DbHopeKurseTextbausteineService } from '../db-hope-kurse-textbausteine.service';
import { SecurityService } from '../security.service';

export class KontakteV1Generated implements AfterViewInit, OnInit, OnDestroy {
  // Components
  @ViewChild('content1') content1: ContentComponent;
  @ViewChild('heading8') heading8: HeadingComponent;
  @ViewChild('heading9') heading9: HeadingComponent;
  @ViewChild('heading16') heading16: HeadingComponent;
  @ViewChild('heading0') heading0: HeadingComponent;
  @ViewChild('heading2') heading2: HeadingComponent;
  @ViewChild('tabs0') tabs0: TabsComponent;
  @ViewChild('gridKontakte') gridKontakte: GridComponent;
  @ViewChild('panel2') panel2: PanelComponent;
  @ViewChild('templateFormKontakte') templateFormKontakte: TemplateFormComponent;
  @ViewChild('label7') label7: LabelComponent;
  @ViewChild('anredeId') anredeId: DropDownComponent;
  @ViewChild('label8') label8: LabelComponent;
  @ViewChild('requiredValidator0') requiredValidator0: RequiredValidatorComponent;
  @ViewChild('name1') name1: TextBoxComponent;
  @ViewChild('label18') label18: LabelComponent;
  @ViewChild('requiredValidator2') requiredValidator2: RequiredValidatorComponent;
  @ViewChild('name2') name2: TextBoxComponent;
  @ViewChild('label9') label9: LabelComponent;
  @ViewChild('requiredValidator1') requiredValidator1: RequiredValidatorComponent;
  @ViewChild('nameKuerzel') nameKuerzel: TextBoxComponent;
  @ViewChild('label10') label10: LabelComponent;
  @ViewChild('titelVorne') titelVorne: TextBoxComponent;
  @ViewChild('titelHinten') titelHinten: TextBoxComponent;
  @ViewChild('label11') label11: LabelComponent;
  @ViewChild('strasse') strasse: TextBoxComponent;
  @ViewChild('label12') label12: LabelComponent;
  @ViewChild('plz') plz: TextBoxComponent;
  @ViewChild('ort') ort: TextBoxComponent;
  @ViewChild('label13') label13: LabelComponent;
  @ViewChild('telefon1') telefon1: TextBoxComponent;
  @ViewChild('label14') label14: LabelComponent;
  @ViewChild('telefon2') telefon2: TextBoxComponent;
  @ViewChild('label15') label15: LabelComponent;
  @ViewChild('eMail1') eMail1: TextBoxComponent;
  @ViewChild('label16') label16: LabelComponent;
  @ViewChild('eMail2') eMail2: TextBoxComponent;
  @ViewChild('label19') label19: LabelComponent;
  @ViewChild('notiz') notiz: TextAreaComponent;
  @ViewChild('button4') button4: ButtonComponent;
  @ViewChild('panel0') panel0: PanelComponent;
  @ViewChild('panel1') panel1: PanelComponent;
  @ViewChild('panel3') panel3: PanelComponent;

  router: Router;

  cd: ChangeDetectorRef;

  route: ActivatedRoute;

  notificationService: NotificationService;

  configService: ConfigService;

  dialogService: DialogService;

  dialogRef: DialogRef;

  httpClient: HttpClient;

  locale: string;

  _location: Location;

  _subscription: Subscription;

  dbHopeKurseTextbausteine: DbHopeKurseTextbausteineService;

  security: SecurityService;
  rstBaseAnreden: any;
  parameters: any;
  rstBaseAlles: any;
  rstBaseAllesCount: any;
  dataBaseAlles: any;
  zeileAusgewaehlt: any;

  constructor(private injector: Injector) {
  }

  ngOnInit() {
    this.notificationService = this.injector.get(NotificationService);

    this.configService = this.injector.get(ConfigService);

    this.dialogService = this.injector.get(DialogService);

    this.dialogRef = this.injector.get(DialogRef, null);

    this.locale = this.injector.get(LOCALE_ID);

    this.router = this.injector.get(Router);

    this.cd = this.injector.get(ChangeDetectorRef);

    this._location = this.injector.get(Location);

    this.route = this.injector.get(ActivatedRoute);

    this.httpClient = this.injector.get(HttpClient);

    this.dbHopeKurseTextbausteine = this.injector.get(DbHopeKurseTextbausteineService);
    this.security = this.injector.get(SecurityService);
  }

  ngAfterViewInit() {
    this._subscription = this.route.params.subscribe(parameters => {
      if (this.dialogRef) {
        this.parameters = this.injector.get(DIALOG_PARAMETERS);
      } else {
        this.parameters = parameters;
      }
      this.load();
      this.cd.detectChanges();
    });
  }

  ngOnDestroy() {
    if (this._subscription) {
      this._subscription.unsubscribe();
    }
  }


  load() {
    this.dbHopeKurseTextbausteine.getBaseAnredens(null, null, null, null, null, null, null, null)
    .subscribe((result: any) => {
      this.rstBaseAnreden = result.value;
    }, (result: any) => {

    });

    this.gridKontakte.load();
  }

  gridKontakteAdd(event: any) {
    this.dialogService.open(KontakteNeuComponent, { parameters: {}, title: `Neuer Kontakt` })
        .afterClosed().subscribe(result => {
              console.log(result);
    });
  }

  gridKontakteDelete(event: any) {
    if (confirm('Are you sure?')) {
          this.dbHopeKurseTextbausteine.deleteBase(event.BaseID)
      .subscribe((result: any) => {
          this.notificationService.notify({ severity: "success", summary: `Success`, detail: `Kontakt gelöscht` });

      this.gridKontakte.load();
      }, (result: any) => {
          this.notificationService.notify({ severity: "error", summary: `Error`, detail: `Kontakt kann nicht gelöscht werden` });
      });
    }
  }

  gridKontakteLoadData(event: any) {
    this.dbHopeKurseTextbausteine.getVwBaseAlles(`${event.filter}`, event.top, event.skip, `${event.orderby || 'Name1, Name2'}`, event.top != null && event.skip != null, null, null, null)
    .subscribe((result: any) => {
      this.rstBaseAlles = result.value;

      this.rstBaseAllesCount = event.top != null && event.skip != null ? result['@odata.count'] : result.value.length;

      this.gridKontakte.onSelect(result.value[0])
    }, (result: any) => {
      this.notificationService.notify({ severity: "error", summary: `Error`, detail: `Kontakte können nicht geladen werden` });
    });
  }

  gridKontakteRowSelect(event: any) {
    this.dataBaseAlles = event;

    this.zeileAusgewaehlt = ((this.gridKontakte.dataTable.anchorRowIndex === null || this.gridKontakte.dataTable.anchorRowIndex === undefined) ? 0 : this.gridKontakte.dataTable.anchorRowIndex) + 1;
  }

  templateFormKontakteSubmit(event: any) {
    this.dbHopeKurseTextbausteine.updateBase(null, this.dataBaseAlles.BaseID, event)
    .subscribe((result: any) => {
      this.notificationService.notify({ severity: "success", summary: `Kontakt erfolgreich gespeichert!`, detail: `` });
    }, (result: any) => {
      this.notificationService.notify({ severity: "error", summary: `Kontakt konnte nicht gespeichert werden!`, detail: `` });
    });
  }
}
