/*
  This file is automatically generated. Any changes will be overwritten.
  Modify add-benutzer-222.component.ts instead.
*/
import { LOCALE_ID, ChangeDetectorRef, ViewChild, AfterViewInit, Injector, OnInit, OnDestroy } from '@angular/core';
import { Router, ActivatedRoute } from '@angular/router';
import { Location } from '@angular/common';
import { HttpClient, HttpParams, HttpHeaders } from '@angular/common/http';
import { Subscription } from 'rxjs';

import { DialogService, DIALOG_PARAMETERS, DialogRef } from '@radzen/angular/dist/dialog';
import { NotificationService } from '@radzen/angular/dist/notification';
import { ContentComponent } from '@radzen/angular/dist/content';
import { TemplateFormComponent } from '@radzen/angular/dist/template-form';
import { LabelComponent } from '@radzen/angular/dist/label';
import { DropDownComponent } from '@radzen/angular/dist/dropdown';
import { RequiredValidatorComponent } from '@radzen/angular/dist/required-validator';
import { TextBoxComponent } from '@radzen/angular/dist/textbox';
import { NumericComponent } from '@radzen/angular/dist/numeric';
import { ButtonComponent } from '@radzen/angular/dist/button';

import { ConfigService } from '../config.service';

import { DbHopeKurseTextbausteineService } from '../db-hope-kurse-textbausteine.service';
import { SecurityService } from '../security.service';

export class AddBenutzer222Generated implements AfterViewInit, OnInit, OnDestroy {
  // Components
  @ViewChild('content1') content1: ContentComponent;
  @ViewChild('form0') form0: TemplateFormComponent;
  @ViewChild('baseIdLabel') baseIdLabel: LabelComponent;
  @ViewChild('baseId') baseId: DropDownComponent;
  @ViewChild('baseIdRequiredValidator') baseIdRequiredValidator: RequiredValidatorComponent;
  @ViewChild('benutzernameLabel') benutzernameLabel: LabelComponent;
  @ViewChild('benutzername') benutzername: TextBoxComponent;
  @ViewChild('benutzernameRequiredValidator') benutzernameRequiredValidator: RequiredValidatorComponent;
  @ViewChild('aspNetUsersIdLabel') aspNetUsersIdLabel: LabelComponent;
  @ViewChild('aspNetUsersId') aspNetUsersId: TextBoxComponent;
  @ViewChild('aspNetUsersIdRequiredValidator') aspNetUsersIdRequiredValidator: RequiredValidatorComponent;
  @ViewChild('initialenLabel') initialenLabel: LabelComponent;
  @ViewChild('initialen') initialen: TextBoxComponent;
  @ViewChild('benutzerEMailLabel') benutzerEMailLabel: LabelComponent;
  @ViewChild('benutzerEMail') benutzerEMail: TextBoxComponent;
  @ViewChild('notizLabel') notizLabel: LabelComponent;
  @ViewChild('notiz') notiz: TextBoxComponent;
  @ViewChild('filterTextbausteinArtCodeLabel') filterTextbausteinArtCodeLabel: LabelComponent;
  @ViewChild('filterTextbausteinArtCode') filterTextbausteinArtCode: TextBoxComponent;
  @ViewChild('filterKursNrLabel') filterKursNrLabel: LabelComponent;
  @ViewChild('filterKursNr') filterKursNr: NumericComponent;
  @ViewChild('filterTitelUndTextLabel') filterTitelUndTextLabel: LabelComponent;
  @ViewChild('filterTitelUndText') filterTitelUndText: TextBoxComponent;
  @ViewChild('filterAutorNrLabel') filterAutorNrLabel: LabelComponent;
  @ViewChild('filterAutorNr') filterAutorNr: NumericComponent;
  @ViewChild('filterThemaNummerLabel') filterThemaNummerLabel: LabelComponent;
  @ViewChild('filterThemaNummer') filterThemaNummer: NumericComponent;
  @ViewChild('filterAnredeLabel') filterAnredeLabel: LabelComponent;
  @ViewChild('filterAnrede') filterAnrede: TextBoxComponent;
  @ViewChild('filterDokumentLabel') filterDokumentLabel: LabelComponent;
  @ViewChild('filterDokument') filterDokument: TextBoxComponent;
  @ViewChild('filterInfoLabel') filterInfoLabel: LabelComponent;
  @ViewChild('filterInfo') filterInfo: TextBoxComponent;
  @ViewChild('button1') button1: ButtonComponent;
  @ViewChild('button2') button2: ButtonComponent;

  router: Router;

  cd: ChangeDetectorRef;

  route: ActivatedRoute;

  notificationService: NotificationService;

  configService: ConfigService;

  dialogService: DialogService;

  dialogRef: DialogRef;

  httpClient: HttpClient;

  locale: string;

  _location: Location;

  _subscription: Subscription;

  dbHopeKurseTextbausteine: DbHopeKurseTextbausteineService;

  security: SecurityService;
  getBasesResult: any;
  parameters: any;

  constructor(private injector: Injector) {
  }

  ngOnInit() {
    this.notificationService = this.injector.get(NotificationService);

    this.configService = this.injector.get(ConfigService);

    this.dialogService = this.injector.get(DialogService);

    this.dialogRef = this.injector.get(DialogRef, null);

    this.locale = this.injector.get(LOCALE_ID);

    this.router = this.injector.get(Router);

    this.cd = this.injector.get(ChangeDetectorRef);

    this._location = this.injector.get(Location);

    this.route = this.injector.get(ActivatedRoute);

    this.httpClient = this.injector.get(HttpClient);

    this.dbHopeKurseTextbausteine = this.injector.get(DbHopeKurseTextbausteineService);
    this.security = this.injector.get(SecurityService);
  }

  ngAfterViewInit() {
    this._subscription = this.route.params.subscribe(parameters => {
      if (this.dialogRef) {
        this.parameters = this.injector.get(DIALOG_PARAMETERS);
      } else {
        this.parameters = parameters;
      }
      this.load();
      this.cd.detectChanges();
    });
  }

  ngOnDestroy() {
    if (this._subscription) {
      this._subscription.unsubscribe();
    }
  }


  load() {
    this.dbHopeKurseTextbausteine.getBases(null, null, null, null, null, null, null, null)
    .subscribe((result: any) => {
      this.getBasesResult = result.value;
    }, (result: any) => {

    });
  }

  form0Submit(event: any) {
    this.dbHopeKurseTextbausteine.createBenutzer(null, event)
    .subscribe((result: any) => {
      if (this.dialogRef) {
        this.dialogRef.close();
      } else {
        this._location.back();
      }
    }, (result: any) => {
      this.notificationService.notify({ severity: "error", summary: `Error`, detail: `Unable to create new Benutzer!` });
    });
  }

  button2Click(event: any) {
    if (this.dialogRef) {
      this.dialogRef.close();
    } else {
      this._location.back();
    }
  }
}
