/*
  This file is automatically generated. Any changes will be overwritten.
  Modify test-base.component.ts instead.
*/
import { LOCALE_ID, ChangeDetectorRef, ViewChild, AfterViewInit, Injector, OnInit, OnDestroy } from '@angular/core';
import { Router, ActivatedRoute } from '@angular/router';
import { Location } from '@angular/common';
import { HttpClient, HttpParams, HttpHeaders } from '@angular/common/http';
import { Subscription } from 'rxjs';

import { DialogService, DIALOG_PARAMETERS, DialogRef } from '@radzen/angular/dist/dialog';
import { NotificationService } from '@radzen/angular/dist/notification';
import { ContentComponent } from '@radzen/angular/dist/content';
import { HeadingComponent } from '@radzen/angular/dist/heading';
import { GridComponent } from '@radzen/angular/dist/grid';

import { ConfigService } from '../config.service';
import { AddBenutzerComponent } from '../add-benutzer/add-benutzer.component';
import { AddTestBaseComponent } from '../add-test-base/add-test-base.component';
import { EditTestBaseComponent } from '../edit-test-base/edit-test-base.component';
import { EditBenutzerComponent } from '../edit-benutzer/edit-benutzer.component';

import { DbHopeKurseTextbausteineService } from '../db-hope-kurse-textbausteine.service';
import { SecurityService } from '../security.service';

export class TestBaseGenerated implements AfterViewInit, OnInit, OnDestroy {
  // Components
  @ViewChild('content1') content1: ContentComponent;
  @ViewChild('pageTitle') pageTitle: HeadingComponent;
  @ViewChild('grid0') grid0: GridComponent;
  @ViewChild('heading1') heading1: HeadingComponent;
  @ViewChild('grid1') grid1: GridComponent;

  router: Router;

  cd: ChangeDetectorRef;

  route: ActivatedRoute;

  notificationService: NotificationService;

  configService: ConfigService;

  dialogService: DialogService;

  dialogRef: DialogRef;

  httpClient: HttpClient;

  locale: string;

  _location: Location;

  _subscription: Subscription;

  dbHopeKurseTextbausteine: DbHopeKurseTextbausteineService;

  security: SecurityService;
  parameters: any;
  getBasesResult: any;
  getBasesCount: any;
  master: any;
  Benutzers: any;

  constructor(private injector: Injector) {
  }

  ngOnInit() {
    this.notificationService = this.injector.get(NotificationService);

    this.configService = this.injector.get(ConfigService);

    this.dialogService = this.injector.get(DialogService);

    this.dialogRef = this.injector.get(DialogRef, null);

    this.locale = this.injector.get(LOCALE_ID);

    this.router = this.injector.get(Router);

    this.cd = this.injector.get(ChangeDetectorRef);

    this._location = this.injector.get(Location);

    this.route = this.injector.get(ActivatedRoute);

    this.httpClient = this.injector.get(HttpClient);

    this.dbHopeKurseTextbausteine = this.injector.get(DbHopeKurseTextbausteineService);
    this.security = this.injector.get(SecurityService);
  }

  ngAfterViewInit() {
    this._subscription = this.route.params.subscribe(parameters => {
      if (this.dialogRef) {
        this.parameters = this.injector.get(DIALOG_PARAMETERS);
      } else {
        this.parameters = parameters;
      }
      this.load();
      this.cd.detectChanges();
    });
  }

  ngOnDestroy() {
    if (this._subscription) {
      this._subscription.unsubscribe();
    }
  }


  load() {
    this.grid0.load();
  }

  grid0LoadData(event: any) {
    this.dbHopeKurseTextbausteine.getBases(`${event.filter}`, event.top, event.skip, `${event.orderby}`, event.top != null && event.skip != null, null, null, null)
    .subscribe((result: any) => {
      this.getBasesResult = result.value;

      this.getBasesCount = event.top != null && event.skip != null ? result['@odata.count'] : result.value.length;

      if (result.value.length && !this.grid0.value) {
        this.grid0.onSelect(result.value[0])
      }
    }, (result: any) => {
      this.notificationService.notify({ severity: "error", summary: `Error`, detail: `Unable to load Bases` });
    });
  }

  grid0Delete(event: any) {
    this.dbHopeKurseTextbausteine.deleteBase(event.BaseID)
    .subscribe((result: any) => {
      this.notificationService.notify({ severity: "success", summary: `Success`, detail: `Base deleted!` });
    }, (result: any) => {
      this.notificationService.notify({ severity: "error", summary: `Error`, detail: `Unable to delete Base` });
    });
  }

  grid0Add(event: any) {
    this.dialogService.open(AddTestBaseComponent, { parameters: {}, title: 'Add Test Base' });
  }

  grid0RowDoubleClick(event: any) {
    this.dialogService.open(EditTestBaseComponent, { parameters: {BaseID: event.BaseID}, title: 'Edit Test Base' });
  }

  grid0RowSelect(event: any) {
    this.master = event;

    this.dbHopeKurseTextbausteine.getBenutzers(`BaseID eq ${event.BaseID}`, null, null, null, null, `Base`, null, null)
    .subscribe((result: any) => {
      this.Benutzers = result.value;
    }, (result: any) => {

    });
  }

  grid1Add(event: any) {
    this.dialogService.open(AddBenutzerComponent, { parameters: {BaseID: this.master.BaseID}, title: 'Add Benutzer' });
  }

  grid1Delete(event: any) {
    this.dbHopeKurseTextbausteine.deleteBenutzer(event.BenutzerID)
    .subscribe((result: any) => {
      this.notificationService.notify({ severity: "success", summary: `Success`, detail: `Benutzer deleted!` });
    }, (result: any) => {
      this.notificationService.notify({ severity: "error", summary: `Error`, detail: `Unable to delete Benutzer` });
    });
  }

  grid1RowSelect(event: any) {
    this.dialogService.open(EditBenutzerComponent, { parameters: {BenutzerID: event.BenutzerID}, title: 'Edit Benutzer' });
  }
}
