/*
  This file is automatically generated. Any changes will be overwritten.
  Modify kontakte.component.ts instead.
*/
import { LOCALE_ID, ChangeDetectorRef, ViewChild, AfterViewInit, Injector, OnInit, OnDestroy } from '@angular/core';
import { Router, ActivatedRoute } from '@angular/router';
import { Location } from '@angular/common';
import { HttpClient, HttpParams, HttpHeaders } from '@angular/common/http';
import { Subscription } from 'rxjs';

import { DialogService, DIALOG_PARAMETERS, DialogRef } from '@radzen/angular/dist/dialog';
import { NotificationService } from '@radzen/angular/dist/notification';
import { ContentComponent } from '@radzen/angular/dist/content';
import { HeadingComponent } from '@radzen/angular/dist/heading';
import { TabsComponent } from '@radzen/angular/dist/tabs';
import { PanelComponent } from '@radzen/angular/dist/panel';
import { GridComponent } from '@radzen/angular/dist/grid';
import { ButtonComponent } from '@radzen/angular/dist/button';
import { TemplateFormComponent } from '@radzen/angular/dist/template-form';
import { LabelComponent } from '@radzen/angular/dist/label';
import { DropDownComponent } from '@radzen/angular/dist/dropdown';
import { RequiredValidatorComponent } from '@radzen/angular/dist/required-validator';
import { TextBoxComponent } from '@radzen/angular/dist/textbox';
import { TextAreaComponent } from '@radzen/angular/dist/textarea';
import { ImageComponent } from '@radzen/angular/dist/image';
import { UploadComponent } from '@radzen/angular/dist/upload';

import { ConfigService } from '../config.service';
import { MeldungJaNeinComponent } from '../meldung-ja-nein/meldung-ja-nein.component';
import { MeldungLoeschenComponent } from '../meldung-loeschen/meldung-loeschen.component';
import { KontakteBearbeitenComponent } from '../kontakte-bearbeiten/kontakte-bearbeiten.component';
import { KontakteNeuComponent } from '../kontakte-neu/kontakte-neu.component';

import { DbHopeKurseTextbausteineService } from '../db-hope-kurse-textbausteine.service';
import { SecurityService } from '../security.service';

export class KontakteGenerated implements AfterViewInit, OnInit, OnDestroy {
  // Components
  @ViewChild('content1') content1: ContentComponent;
  @ViewChild('heading8') heading8: HeadingComponent;
  @ViewChild('heading9') heading9: HeadingComponent;
  @ViewChild('heading2') heading2: HeadingComponent;
  @ViewChild('tabs0') tabs0: TabsComponent;
  @ViewChild('panel0') panel0: PanelComponent;
  @ViewChild('gridKontakte') gridKontakte: GridComponent;
  @ViewChild('buttonNeu') buttonNeu: ButtonComponent;
  @ViewChild('buttonBearbeiten') buttonBearbeiten: ButtonComponent;
  @ViewChild('buttonLoeschen') buttonLoeschen: ButtonComponent;
  @ViewChild('panel2') panel2: PanelComponent;
  @ViewChild('templateFormKontakte') templateFormKontakte: TemplateFormComponent;
  @ViewChild('label7') label7: LabelComponent;
  @ViewChild('anredeId') anredeId: DropDownComponent;
  @ViewChild('label8') label8: LabelComponent;
  @ViewChild('requiredValidator0') requiredValidator0: RequiredValidatorComponent;
  @ViewChild('name1') name1: TextBoxComponent;
  @ViewChild('label18') label18: LabelComponent;
  @ViewChild('requiredValidator2') requiredValidator2: RequiredValidatorComponent;
  @ViewChild('name2') name2: TextBoxComponent;
  @ViewChild('label9') label9: LabelComponent;
  @ViewChild('requiredValidator1') requiredValidator1: RequiredValidatorComponent;
  @ViewChild('nameKuerzel') nameKuerzel: TextBoxComponent;
  @ViewChild('label10') label10: LabelComponent;
  @ViewChild('titelVorne') titelVorne: TextBoxComponent;
  @ViewChild('titelHinten') titelHinten: TextBoxComponent;
  @ViewChild('label11') label11: LabelComponent;
  @ViewChild('strasse') strasse: TextBoxComponent;
  @ViewChild('label12') label12: LabelComponent;
  @ViewChild('plz') plz: TextBoxComponent;
  @ViewChild('ort') ort: TextBoxComponent;
  @ViewChild('label13') label13: LabelComponent;
  @ViewChild('telefon1') telefon1: TextBoxComponent;
  @ViewChild('label14') label14: LabelComponent;
  @ViewChild('telefon2') telefon2: TextBoxComponent;
  @ViewChild('label15') label15: LabelComponent;
  @ViewChild('eMail1') eMail1: TextBoxComponent;
  @ViewChild('label16') label16: LabelComponent;
  @ViewChild('eMail2') eMail2: TextBoxComponent;
  @ViewChild('label19') label19: LabelComponent;
  @ViewChild('notiz') notiz: TextAreaComponent;
  @ViewChild('button4') button4: ButtonComponent;
  @ViewChild('panel3') panel3: PanelComponent;
  @ViewChild('formBenutzer') formBenutzer: TemplateFormComponent;
  @ViewChild('benutzernameLabel') benutzernameLabel: LabelComponent;
  @ViewChild('benutzername') benutzername: TextBoxComponent;
  @ViewChild('initialenLabel') initialenLabel: LabelComponent;
  @ViewChild('initialen') initialen: TextBoxComponent;
  @ViewChild('benutzerEMailLabel') benutzerEMailLabel: LabelComponent;
  @ViewChild('benutzerEMail') benutzerEMail: TextBoxComponent;
  @ViewChild('notizLabel') notizLabel: LabelComponent;
  @ViewChild('textarea0') textarea0: TextAreaComponent;
  @ViewChild('panel1') panel1: PanelComponent;
  @ViewChild('bild') bild: PanelComponent;
  @ViewChild('bildUrl') bildUrl: ImageComponent;
  @ViewChild('uploadBildBase') uploadBildBase: UploadComponent;
  @ViewChild('buttonBildEntfernen') buttonBildEntfernen: ButtonComponent;

  router: Router;

  cd: ChangeDetectorRef;

  route: ActivatedRoute;

  notificationService: NotificationService;

  configService: ConfigService;

  dialogService: DialogService;

  dialogRef: DialogRef;

  httpClient: HttpClient;

  locale: string;

  _location: Location;

  _subscription: Subscription;

  dbHopeKurseTextbausteine: DbHopeKurseTextbausteineService;

  security: SecurityService;
  letzteBaseID: any;
  rstBaseAnreden: any;
  parameters: any;
  rstBase: any;
  rstBaseCount: any;
  dsoBase: any;
  dsoBenutzer: any;

  constructor(private injector: Injector) {
  }

  ngOnInit() {
    this.notificationService = this.injector.get(NotificationService);

    this.configService = this.injector.get(ConfigService);

    this.dialogService = this.injector.get(DialogService);

    this.dialogRef = this.injector.get(DialogRef, null);

    this.locale = this.injector.get(LOCALE_ID);

    this.router = this.injector.get(Router);

    this.cd = this.injector.get(ChangeDetectorRef);

    this._location = this.injector.get(Location);

    this.route = this.injector.get(ActivatedRoute);

    this.httpClient = this.injector.get(HttpClient);

    this.dbHopeKurseTextbausteine = this.injector.get(DbHopeKurseTextbausteineService);
    this.security = this.injector.get(SecurityService);
  }

  ngAfterViewInit() {
    this._subscription = this.route.params.subscribe(parameters => {
      if (this.dialogRef) {
        this.parameters = this.injector.get(DIALOG_PARAMETERS);
      } else {
        this.parameters = parameters;
      }
      this.load();
      this.cd.detectChanges();
    });
  }

  ngOnDestroy() {
    if (this._subscription) {
      this._subscription.unsubscribe();
    }
  }


  load() {
    this.letzteBaseID = null;

    this.dbHopeKurseTextbausteine.getBaseAnredens(null, null, null, null, null, null, null, null)
    .subscribe((result: any) => {
      this.rstBaseAnreden = result.value;

      this.gridKontakte.load();
    }, (result: any) => {

    });
  }

  gridKontakteLoadData(event: any) {
    this.dbHopeKurseTextbausteine.getBases(`${event.filter}`, event.top, event.skip, `${event.orderby || 'Name1, Name2'}`, event.top != null && event.skip != null, `BaseAnreden`, null, null)
    .subscribe((result: any) => {
      this.rstBase = result.value;

      this.rstBaseCount = event.top != null && event.skip != null ? result['@odata.count'] : result.value.length;

      if (this.rstBase.find(p => p.BaseID == this.letzteBaseID) != null) {
    // letzteBaseID wurde in rstBase gefunden
    this.gridKontakte.onSelect(this.rstBase.find(p => p.BaseID == this.letzteBaseID))
} else {
    // letzteBaseID wurde in rstBaseID NICHT gefunden
    this.letzteBaseID = null;
    this.gridKontakte.onSelect(this.rstBase[0]);
}
    }, (result: any) => {
      this.notificationService.notify({ severity: "error", summary: ``, detail: `Kontakte können nicht geladen werden!` });
    });
  }

  gridKontakteRowDoubleClick(event: any) {
    this.letzteBaseID = this.dsoBase.BaseID;

    this.dialogService.open(KontakteBearbeitenComponent, { parameters: {BaseID: event.BaseID}, title: `Bearbeiten Kontakt` });
  }

  gridKontakteRowSelect(event: any) {
    this.dsoBase = event;

    this.dbHopeKurseTextbausteine.getBenutzers(`BaseID eq ${event.BaseID}`, null, null, null, null, null, null, null)
    .subscribe((result: any) => {
      this.dsoBenutzer = result.value[0];
    }, (result: any) => {

    });
  }

  buttonNeuClick(event: any) {
    this.letzteBaseID = this.dsoBase.BaseID;

    this.dialogService.open(KontakteNeuComponent, { parameters: {}, title: `Neuer Kontakt` })
        .afterClosed().subscribe(result => {
              if (result != null) {
            this.letzteBaseID = result.BaseID;
      }

      if (result != null) {
        this.gridKontakte.load();
      }
    });
  }

  buttonBearbeitenClick(event: any) {
    this.letzteBaseID = this.dsoBase.BaseID;

    this.dialogService.open(KontakteBearbeitenComponent, { parameters: {BaseID: this.dsoBase.BaseID}, title: `Bearbeiten Kontakt` });
  }

  buttonLoeschenClick(event: any) {
    this.letzteBaseID = null;

    this.dialogService.open(MeldungLoeschenComponent, { parameters: {strMeldung: "Soll der Kontakt '" + this.dsoBase.Name1 + " " + this.dsoBase.Name2 + "' gelöscht werden?"}, title: `Löschen Kontakt` })
        .afterClosed().subscribe(result => {
              if (result == 'Löschen') {
              this.dbHopeKurseTextbausteine.deleteBase(this.dsoBase.BaseID)
        .subscribe((result: any) => {
              this.notificationService.notify({ severity: "success", summary: ``, detail: `Kontakt gelöscht` });
        }, (result: any) => {
              this.notificationService.notify({ severity: "error", summary: ``, detail: `Kontakt konnte nicht gelöscht werden!` });
        });
      }
    });
  }

  button4Click(event: any) {
    this.dbHopeKurseTextbausteine.updateBase(null, this.dsoBase.BaseID, this.dsoBase)
    .subscribe((result: any) => {
      this.notificationService.notify({ severity: "success", summary: ``, detail: `Änderungen gespeichert` });
    }, (result: any) => {
      this.notificationService.notify({ severity: "error", summary: ``, detail: `Änderungen konnten nicht gespeichert werden!` });
    });
  }

  uploadBildBaseBeforeUpload(event: any) {
    var strDateiName = this.uploadBildBase.fileUpload.files[0].name;
var strDateiEndung = strDateiName.substring(strDateiName.indexOf("."));

this.dsoBase.BildURL = 'https://hopekurse-textbausteine.app/upload/bilder/base/KeinBildPerson.png';
this.dsoBase.BildURL = 'https://hopekurse-textbausteine.app/upload/bilder/base/' + this.dsoBase.BaseID + strDateiEndung;
  }

  uploadBildBaseError(event: any) {
    this.notificationService.notify({ severity: "error", summary: `Bild`, detail: `Hochladen fehlgeschlagen!` });
  }

  uploadBildBaseUpload(event: any) {
    this.dbHopeKurseTextbausteine.updateBase(null, this.dsoBase.BaseID, this.dsoBase)
    .subscribe((result: any) => {

    }, (result: any) => {

    });

    this.notificationService.notify({ severity: "success", summary: `Bild`, detail: `Erfolgreich hochgeladen!` });
  }

  buttonBildEntfernenClick(event: any) {
    this.dialogService.open(MeldungJaNeinComponent, { parameters: {strMeldung: "Soll das Bild von '" + this.dsoBase.Name1 + " " + this.dsoBase.Name2 + "' entfernt werden?"}, title: `Bild entfernen` })
        .afterClosed().subscribe(result => {
              if (result == 'Ja') {
        this.dsoBase.BildURL = 'https://hopekurse-textbausteine.app/upload/bilder/base/KeinBildPerson.png';
      }

      if (result == 'Ja') {
              this.dbHopeKurseTextbausteine.updateBase(null, this.dsoBase.BaseID, this.dsoBase)
        .subscribe((result: any) => {
              this.notificationService.notify({ severity: "success", summary: ``, detail: `Bild entfernt` });
        }, (result: any) => {
              this.notificationService.notify({ severity: "error", summary: ``, detail: `Bild konnte nicht entfernt werden!` });
        });
      }
    });
  }
}
