/*
  This file is automatically generated. Any changes will be overwritten.
  Modify dokumente.component.ts instead.
*/
import { LOCALE_ID, ChangeDetectorRef, ViewChild, AfterViewInit, Injector, OnInit, OnDestroy } from '@angular/core';
import { Router, ActivatedRoute } from '@angular/router';
import { Location } from '@angular/common';
import { HttpClient, HttpParams, HttpHeaders } from '@angular/common/http';
import { Subscription } from 'rxjs';

import { DialogService, DIALOG_PARAMETERS, DialogRef } from '@radzen/angular/dist/dialog';
import { NotificationService } from '@radzen/angular/dist/notification';
import { ContentComponent } from '@radzen/angular/dist/content';
import { HeadingComponent } from '@radzen/angular/dist/heading';
import { TabsComponent } from '@radzen/angular/dist/tabs';
import { PanelComponent } from '@radzen/angular/dist/panel';
import { GridComponent } from '@radzen/angular/dist/grid';
import { ButtonComponent } from '@radzen/angular/dist/button';
import { HtmlComponent } from '@radzen/angular/dist/html';

import { ConfigService } from '../config.service';
import { DokumenteEditorComponent } from '../dokumente-editor/dokumente-editor.component';
import { TextbausteineDokumenteComponent } from '../textbausteine-dokumente/textbausteine-dokumente.component';
import { MeldungLoeschenComponent } from '../meldung-loeschen/meldung-loeschen.component';
import { TextbausteineBearbeitenComponent } from '../textbausteine-bearbeiten/textbausteine-bearbeiten.component';

import { DbHopeKurseTextbausteineService } from '../db-hope-kurse-textbausteine.service';
import { SecurityService } from '../security.service';

export class DokumenteGenerated implements AfterViewInit, OnInit, OnDestroy {
  // Components
  @ViewChild('content1') content1: ContentComponent;
  @ViewChild('heading18') heading18: HeadingComponent;
  @ViewChild('heading19') heading19: HeadingComponent;
  @ViewChild('heading21') heading21: HeadingComponent;
  @ViewChild('tabs0') tabs0: TabsComponent;
  @ViewChild('panel8') panel8: PanelComponent;
  @ViewChild('gridTextbausteineDokumente') gridTextbausteineDokumente: GridComponent;
  @ViewChild('buttonDokumenteBearbeiten') buttonDokumenteBearbeiten: ButtonComponent;
  @ViewChild('buttonDokumenteLoeschen') buttonDokumenteLoeschen: ButtonComponent;
  @ViewChild('panel9') panel9: PanelComponent;
  @ViewChild('html1') html1: HtmlComponent;
  @ViewChild('buttonDokumenteDokument') buttonDokumenteDokument: ButtonComponent;
  @ViewChild('buttonKopieren') buttonKopieren: ButtonComponent;
  @ViewChild('buttonBearbeitenEditor') buttonBearbeitenEditor: ButtonComponent;

  router: Router;

  cd: ChangeDetectorRef;

  route: ActivatedRoute;

  notificationService: NotificationService;

  configService: ConfigService;

  dialogService: DialogService;

  dialogRef: DialogRef;

  httpClient: HttpClient;

  locale: string;

  _location: Location;

  _subscription: Subscription;

  dbHopeKurseTextbausteine: DbHopeKurseTextbausteineService;

  security: SecurityService;
  letzteTextbausteinNr: any;
  strTextbausteinDokumenteHTML: any;
  parameters: any;
  rstTextbausteineDokumente: any;
  rstTextbausteineDokumenteCount: any;
  dsoTextbausteineDokumente: any;

  constructor(private injector: Injector) {
  }

  ngOnInit() {
    this.notificationService = this.injector.get(NotificationService);

    this.configService = this.injector.get(ConfigService);

    this.dialogService = this.injector.get(DialogService);

    this.dialogRef = this.injector.get(DialogRef, null);

    this.locale = this.injector.get(LOCALE_ID);

    this.router = this.injector.get(Router);

    this.cd = this.injector.get(ChangeDetectorRef);

    this._location = this.injector.get(Location);

    this.route = this.injector.get(ActivatedRoute);

    this.httpClient = this.injector.get(HttpClient);

    this.dbHopeKurseTextbausteine = this.injector.get(DbHopeKurseTextbausteineService);
    this.security = this.injector.get(SecurityService);
  }

  ngAfterViewInit() {
    this._subscription = this.route.params.subscribe(parameters => {
      if (this.dialogRef) {
        this.parameters = this.injector.get(DIALOG_PARAMETERS);
      } else {
        this.parameters = parameters;
      }
      this.load();
      this.cd.detectChanges();
    });
  }

  ngOnDestroy() {
    if (this._subscription) {
      this._subscription.unsubscribe();
    }
  }


  load() {
    this.letzteTextbausteinNr = null;

    this.gridTextbausteineDokumente.load();

    this.strTextbausteinDokumenteHTML = null;
  }

  gridTextbausteineDokumenteLoadData(event: any) {
    this.dbHopeKurseTextbausteine.getIbsiTextbausteines(`DokumentTitel ne null and Ordner ne 'Papierkorb'`, event.top, event.skip, `${event.orderby || 'TitelTextbaustein'}`, event.top != null && event.skip != null, `IBSITextbausteineAutoren, IBSIKurse`, null, null)
    .subscribe((result: any) => {
      this.rstTextbausteineDokumente = result.value;

      this.rstTextbausteineDokumenteCount = event.top != null && event.skip != null ? result['@odata.count'] : result.value.length;

      if (this.rstTextbausteineDokumente.find(p => p.TextbausteinNr == this.letzteTextbausteinNr) != null) {
    // letzteTextbausteinNr wurde in rstTextbausteineDokumente gefunden
    this.gridTextbausteineDokumente.onSelect(this.rstTextbausteineDokumente.find(p => p.TextbausteinNr == this.letzteTextbausteinNr))
} else {
    // letzteTextbausteinNr wurde in rstTextbausteineDokumente NICHT gefunden
    this.letzteTextbausteinNr = null;
    this.gridTextbausteineDokumente.onSelect(this.rstTextbausteineDokumente[0]);
}
    }, (result: any) => {
      this.notificationService.notify({ severity: "error", summary: ``, detail: `Dokumente konnten nicht geladen werden!` });
    });
  }

  gridTextbausteineDokumenteRowDoubleClick(event: any) {
    this.letzteTextbausteinNr = this.dsoTextbausteineDokumente.TextbausteinNr;

    this.dialogService.open(TextbausteineBearbeitenComponent, { parameters: {TextbausteinNr: this.dsoTextbausteineDokumente.TextbausteinNr}, title: `Bearbeiten Textbaustein` });
  }

  gridTextbausteineDokumenteRowSelect(event: any) {
    this.strTextbausteinDokumenteHTML = event.TextbausteinHTML;

    this.dsoTextbausteineDokumente = event;
  }

  buttonDokumenteBearbeitenClick(event: any) {
    this.letzteTextbausteinNr = this.dsoTextbausteineDokumente.TextbausteinNr;

    this.dialogService.open(TextbausteineBearbeitenComponent, { parameters: {TextbausteinNr: this.dsoTextbausteineDokumente.TextbausteinNr}, title: `Bearbeiten Textbaustein` });
  }

  buttonDokumenteLoeschenClick(event: any) {
    this.letzteTextbausteinNr = null;

    this.dialogService.open(MeldungLoeschenComponent, { parameters: {strMeldung: "Soll der Textbaustein '" + this.dsoTextbausteineDokumente.TitelTextbaustein + "' gelöscht (in den Papierkorb) werden?"}, title: `Löschen Textbaustein` })
        .afterClosed().subscribe(result => {
              if (result == 'Löschen') {
        this.dsoTextbausteineDokumente.Ordner = 'Papierkorb'
      }

      if (result == 'Löschen') {
              this.dbHopeKurseTextbausteine.updateIbsiTextbausteine(null, this.dsoTextbausteineDokumente.TextbausteinNr, this.dsoTextbausteineDokumente)
        .subscribe((result: any) => {
              this.gridTextbausteineDokumente.load();

        this.notificationService.notify({ severity: "success", summary: ``, detail: `Textbaustein gelöscht` });
        }, (result: any) => {
              this.notificationService.notify({ severity: "error", summary: ``, detail: `Textbaustein konnte nicht gelöscht werden!` });
        });
      }
    });
  }

  buttonDokumenteDokumentClick(event: any) {
    this.dialogService.open(TextbausteineDokumenteComponent, { parameters: {TextbausteinNr: this.dsoTextbausteineDokumente.TextbausteinNr}, width: 900, title: `Textbaustein Dokument` });
  }

  buttonKopierenClick(event: any) {
      // Create container for the HTML
  // [1]
  var container = document.createElement('div')
  container.innerHTML = this.strTextbausteinDokumenteHTML

  // Hide element
  // [2]
  container.style.position = 'fixed'
  container.style.pointerEvents = 'none'
  container.style.opacity = '0'
  container.style.background = 'white'

  // Mount the container to the DOM to make `contentWindow` available
  // [3]
  document.body.appendChild(container)

  // Copy to clipboard
  // [4]
  window.getSelection().removeAllRanges()

  var range = document.createRange()
  range.selectNode(container)
  window.getSelection().addRange(range)

  // [5]
  document.execCommand('copy')
  
  // Remove the container
  // [6]
  document.body.removeChild(container)

    this.notificationService.notify({ severity: "success", summary: ``, detail: `Text wurde kopiert` });
  }

  buttonBearbeitenEditorClick(event: any) {
    this.letzteTextbausteinNr = this.dsoTextbausteineDokumente.TextbausteinNr;

    this.dialogService.open(DokumenteEditorComponent, { parameters: {TextbausteinNr: this.dsoTextbausteineDokumente.TextbausteinNr}, width: 720, title: `Bearbeiten` });
  }
}
