/*
  This file is automatically generated. Any changes will be overwritten.
  Modify kurse-themen-bearbeiten.component.ts instead.
*/
import { LOCALE_ID, ChangeDetectorRef, ViewChild, AfterViewInit, Injector, OnInit, OnDestroy } from '@angular/core';
import { Router, ActivatedRoute } from '@angular/router';
import { Location } from '@angular/common';
import { HttpClient, HttpParams, HttpHeaders } from '@angular/common/http';
import { Subscription } from 'rxjs';

import { DialogService, DIALOG_PARAMETERS, DialogRef } from '@radzen/angular/dist/dialog';
import { NotificationService } from '@radzen/angular/dist/notification';
import { ContentComponent } from '@radzen/angular/dist/content';
import { TemplateFormComponent } from '@radzen/angular/dist/template-form';
import { LabelComponent } from '@radzen/angular/dist/label';
import { DropDownComponent } from '@radzen/angular/dist/dropdown';
import { RequiredValidatorComponent } from '@radzen/angular/dist/required-validator';
import { NumericComponent } from '@radzen/angular/dist/numeric';
import { TextBoxComponent } from '@radzen/angular/dist/textbox';
import { TextAreaComponent } from '@radzen/angular/dist/textarea';
import { ButtonComponent } from '@radzen/angular/dist/button';

import { ConfigService } from '../config.service';

import { DbHopeKurseTextbausteineService } from '../db-hope-kurse-textbausteine.service';
import { SecurityService } from '../security.service';

export class KurseThemenBearbeitenGenerated implements AfterViewInit, OnInit, OnDestroy {
  // Components
  @ViewChild('content1') content1: ContentComponent;
  @ViewChild('form0') form0: TemplateFormComponent;
  @ViewChild('kursNrLabel') kursNrLabel: LabelComponent;
  @ViewChild('kursNr') kursNr: DropDownComponent;
  @ViewChild('kursNrRequiredValidator') kursNrRequiredValidator: RequiredValidatorComponent;
  @ViewChild('nummerLabel') nummerLabel: LabelComponent;
  @ViewChild('nummer') nummer: NumericComponent;
  @ViewChild('nummerRequiredValidator') nummerRequiredValidator: RequiredValidatorComponent;
  @ViewChild('titelLabel') titelLabel: LabelComponent;
  @ViewChild('titel') titel: TextBoxComponent;
  @ViewChild('untertitelLabel') untertitelLabel: LabelComponent;
  @ViewChild('untertitel') untertitel: TextBoxComponent;
  @ViewChild('kurzbeschreibungLabel') kurzbeschreibungLabel: LabelComponent;
  @ViewChild('kurzbeschreibung') kurzbeschreibung: TextAreaComponent;
  @ViewChild('begleitmaterialLabel') begleitmaterialLabel: LabelComponent;
  @ViewChild('begleitmaterial') begleitmaterial: TextAreaComponent;
  @ViewChild('druckfehlerLabel') druckfehlerLabel: LabelComponent;
  @ViewChild('druckfehler') druckfehler: TextAreaComponent;
  @ViewChild('infoMemoLabel') infoMemoLabel: LabelComponent;
  @ViewChild('infoMemo') infoMemo: TextAreaComponent;
  @ViewChild('button0') button0: ButtonComponent;
  @ViewChild('button1') button1: ButtonComponent;

  router: Router;

  cd: ChangeDetectorRef;

  route: ActivatedRoute;

  notificationService: NotificationService;

  configService: ConfigService;

  dialogService: DialogService;

  dialogRef: DialogRef;

  httpClient: HttpClient;

  locale: string;

  _location: Location;

  _subscription: Subscription;

  dbHopeKurseTextbausteine: DbHopeKurseTextbausteineService;

  security: SecurityService;
  dsoKurseThemen: any;
  rstKurse: any;
  parameters: any;

  constructor(private injector: Injector) {
  }

  ngOnInit() {
    this.notificationService = this.injector.get(NotificationService);

    this.configService = this.injector.get(ConfigService);

    this.dialogService = this.injector.get(DialogService);

    this.dialogRef = this.injector.get(DialogRef, null);

    this.locale = this.injector.get(LOCALE_ID);

    this.router = this.injector.get(Router);

    this.cd = this.injector.get(ChangeDetectorRef);

    this._location = this.injector.get(Location);

    this.route = this.injector.get(ActivatedRoute);

    this.httpClient = this.injector.get(HttpClient);

    this.dbHopeKurseTextbausteine = this.injector.get(DbHopeKurseTextbausteineService);
    this.security = this.injector.get(SecurityService);
  }

  ngAfterViewInit() {
    this._subscription = this.route.params.subscribe(parameters => {
      if (this.dialogRef) {
        this.parameters = this.injector.get(DIALOG_PARAMETERS);
      } else {
        this.parameters = parameters;
      }
      this.load();
      this.cd.detectChanges();
    });
  }

  ngOnDestroy() {
    if (this._subscription) {
      this._subscription.unsubscribe();
    }
  }


  load() {
    this.dbHopeKurseTextbausteine.getIbsiKurseThemenByKursThemaNr(null, this.parameters.KursThemaNr)
    .subscribe((result: any) => {
      this.dsoKurseThemen = result;
    }, (result: any) => {

    });

    this.dbHopeKurseTextbausteine.getIbsiKurses(null, null, null, `Titel`, null, null, null, `KursNr, Titel`)
    .subscribe((result: any) => {
      this.rstKurse = result.value;
    }, (result: any) => {

    });
  }

  form0Submit(event: any) {
    this.dbHopeKurseTextbausteine.updateIbsiKurseThemen(null, this.parameters.KursThemaNr, event)
    .subscribe((result: any) => {
      this.notificationService.notify({ severity: "success", summary: `Thema erfolgreich gespeichert`, detail: `` });

      this.dialogRef.close(result);
    }, (result: any) => {
      this.notificationService.notify({ severity: "error", summary: `Thema konnte nicht gespeichert werden!`, detail: `` });
    });
  }

  button1Click(event: any) {
    if (this.dialogRef) {
      this.dialogRef.close();
    } else {
      this._location.back();
    }
  }
}
