/*
  This file is automatically generated. Any changes will be overwritten.
  Modify ibsi-kurse.component.ts instead.
*/
import { LOCALE_ID, ChangeDetectorRef, ViewChild, AfterViewInit, Injector, OnInit, OnDestroy } from '@angular/core';
import { Router, ActivatedRoute } from '@angular/router';
import { Location } from '@angular/common';
import { HttpClient, HttpParams, HttpHeaders } from '@angular/common/http';
import { Subscription } from 'rxjs';

import { DialogService, DIALOG_PARAMETERS, DialogRef } from '@radzen/angular/dist/dialog';
import { NotificationService } from '@radzen/angular/dist/notification';
import { ContentComponent } from '@radzen/angular/dist/content';
import { HeadingComponent } from '@radzen/angular/dist/heading';
import { GridComponent } from '@radzen/angular/dist/grid';

import { ConfigService } from '../config.service';
import { KurseThemenNeuComponent } from '../kurse-themen-neu/kurse-themen-neu.component';
import { KurseNeuComponent } from '../kurse-neu/kurse-neu.component';
import { KurseBearbeitenComponent } from '../kurse-bearbeiten/kurse-bearbeiten.component';
import { KurseThemenBearbeitenComponent } from '../kurse-themen-bearbeiten/kurse-themen-bearbeiten.component';

import { DbHopeKurseTextbausteineService } from '../db-hope-kurse-textbausteine.service';
import { SecurityService } from '../security.service';

export class IbsiKurseGenerated implements AfterViewInit, OnInit, OnDestroy {
  // Components
  @ViewChild('content1') content1: ContentComponent;
  @ViewChild('pageTitle') pageTitle: HeadingComponent;
  @ViewChild('grid0') grid0: GridComponent;
  @ViewChild('heading1') heading1: HeadingComponent;
  @ViewChild('grid1') grid1: GridComponent;

  router: Router;

  cd: ChangeDetectorRef;

  route: ActivatedRoute;

  notificationService: NotificationService;

  configService: ConfigService;

  dialogService: DialogService;

  dialogRef: DialogRef;

  httpClient: HttpClient;

  locale: string;

  _location: Location;

  _subscription: Subscription;

  dbHopeKurseTextbausteine: DbHopeKurseTextbausteineService;

  security: SecurityService;
  parameters: any;
  getIbsiKursesResult: any;
  getIbsiKursesCount: any;
  master: any;
  IbsiKurseThemens: any;

  constructor(private injector: Injector) {
  }

  ngOnInit() {
    this.notificationService = this.injector.get(NotificationService);

    this.configService = this.injector.get(ConfigService);

    this.dialogService = this.injector.get(DialogService);

    this.dialogRef = this.injector.get(DialogRef, null);

    this.locale = this.injector.get(LOCALE_ID);

    this.router = this.injector.get(Router);

    this.cd = this.injector.get(ChangeDetectorRef);

    this._location = this.injector.get(Location);

    this.route = this.injector.get(ActivatedRoute);

    this.httpClient = this.injector.get(HttpClient);

    this.dbHopeKurseTextbausteine = this.injector.get(DbHopeKurseTextbausteineService);
    this.security = this.injector.get(SecurityService);
  }

  ngAfterViewInit() {
    this._subscription = this.route.params.subscribe(parameters => {
      if (this.dialogRef) {
        this.parameters = this.injector.get(DIALOG_PARAMETERS);
      } else {
        this.parameters = parameters;
      }
      this.load();
      this.cd.detectChanges();
    });
  }

  ngOnDestroy() {
    if (this._subscription) {
      this._subscription.unsubscribe();
    }
  }


  load() {
    this.grid0.load();
  }

  grid0LoadData(event: any) {
    this.dbHopeKurseTextbausteine.getIbsiKurses(`${event.filter}`, event.top, event.skip, `${event.orderby}`, event.top != null && event.skip != null, `IbsiKurseArten`, null, null)
    .subscribe((result: any) => {
      this.getIbsiKursesResult = result.value;

      this.getIbsiKursesCount = event.top != null && event.skip != null ? result['@odata.count'] : result.value.length;

      if (result.value.length && !this.grid0.value) {
        this.grid0.onSelect(result.value[0])
      }
    }, (result: any) => {
      this.notificationService.notify({ severity: "error", summary: `Error`, detail: `Unable to load IbsiKurses` });
    });
  }

  grid0Delete(event: any) {
    this.dbHopeKurseTextbausteine.deleteIbsiKurse(event.KursNr)
    .subscribe((result: any) => {
      this.notificationService.notify({ severity: "success", summary: `Success`, detail: `IbsiKurse deleted!` });
    }, (result: any) => {
      this.notificationService.notify({ severity: "error", summary: `Error`, detail: `Unable to delete IbsiKurse` });
    });
  }

  grid0Add(event: any) {
    this.dialogService.open(KurseNeuComponent, { parameters: {}, title: 'KurseNeu' });
  }

  grid0RowDoubleClick(event: any) {
    this.dialogService.open(KurseBearbeitenComponent, { parameters: {KursNr: event.KursNr}, title: 'KurseBearbeiten' });
  }

  grid0RowSelect(event: any) {
    this.master = event;

    this.dbHopeKurseTextbausteine.getIbsiKurseThemens(`KursNr eq ${event.KursNr}`, null, null, null, null, `IbsiKurse`, null, null)
    .subscribe((result: any) => {
      this.IbsiKurseThemens = result.value;
    }, (result: any) => {

    });
  }

  grid1Add(event: any) {
    this.dialogService.open(KurseThemenNeuComponent, { parameters: {KursNr: this.master.KursNr}, title: 'KurseThemenNeu' });
  }

  grid1Delete(event: any) {
    this.dbHopeKurseTextbausteine.deleteIbsiKurseThemen(event.KursThemaNr)
    .subscribe((result: any) => {
      this.notificationService.notify({ severity: "success", summary: `Success`, detail: `IbsiKurseThemen deleted!` });
    }, (result: any) => {
      this.notificationService.notify({ severity: "error", summary: `Error`, detail: `Unable to delete IbsiKurseThemen` });
    });
  }

  grid1RowSelect(event: any) {
    this.dialogService.open(KurseThemenBearbeitenComponent, { parameters: {KursThemaNr: event.KursThemaNr}, title: 'KurseThemenBearbeiten' });
  }
}
