/*
  This file is automatically generated. Any changes will be overwritten.
  Modify autoren.component.ts instead.
*/
import { LOCALE_ID, ChangeDetectorRef, ViewChild, AfterViewInit, Injector, OnInit, OnDestroy } from '@angular/core';
import { Router, ActivatedRoute } from '@angular/router';
import { Location } from '@angular/common';
import { HttpClient, HttpParams, HttpHeaders } from '@angular/common/http';
import { Subscription } from 'rxjs';

import { DialogService, DIALOG_PARAMETERS, DialogRef } from '@radzen/angular/dist/dialog';
import { NotificationService } from '@radzen/angular/dist/notification';
import { ContentComponent } from '@radzen/angular/dist/content';
import { HeadingComponent } from '@radzen/angular/dist/heading';
import { TabsComponent } from '@radzen/angular/dist/tabs';
import { PanelComponent } from '@radzen/angular/dist/panel';
import { GridComponent } from '@radzen/angular/dist/grid';
import { TextBoxComponent } from '@radzen/angular/dist/textbox';
import { ButtonComponent } from '@radzen/angular/dist/button';

import { ConfigService } from '../config.service';
import { MeldungLoeschenComponent } from '../meldung-loeschen/meldung-loeschen.component';
import { AutorenBearbeitenComponent } from '../autoren-bearbeiten/autoren-bearbeiten.component';
import { AutorenNeuComponent } from '../autoren-neu/autoren-neu.component';

import { DbHopeKurseTextbausteineService } from '../db-hope-kurse-textbausteine.service';
import { SecurityService } from '../security.service';

export class AutorenGenerated implements AfterViewInit, OnInit, OnDestroy {
  // Components
  @ViewChild('content1') content1: ContentComponent;
  @ViewChild('heading18') heading18: HeadingComponent;
  @ViewChild('heading19') heading19: HeadingComponent;
  @ViewChild('heading21') heading21: HeadingComponent;
  @ViewChild('tabs0') tabs0: TabsComponent;
  @ViewChild('panel1') panel1: PanelComponent;
  @ViewChild('gridAutoren') gridAutoren: GridComponent;
  @ViewChild('buttonNeu') buttonNeu: ButtonComponent;
  @ViewChild('buttonBearbeiten') buttonBearbeiten: ButtonComponent;
  @ViewChild('buttonLoeschen') buttonLoeschen: ButtonComponent;
  @ViewChild('panel0') panel0: PanelComponent;
  @ViewChild('gridTextbausteine') gridTextbausteine: GridComponent;

  router: Router;

  cd: ChangeDetectorRef;

  route: ActivatedRoute;

  notificationService: NotificationService;

  configService: ConfigService;

  dialogService: DialogService;

  dialogRef: DialogRef;

  httpClient: HttpClient;

  locale: string;

  _location: Location;

  _subscription: Subscription;

  dbHopeKurseTextbausteine: DbHopeKurseTextbausteineService;

  security: SecurityService;
  parameters: any;
  letzteAutorNr: any;
  rstAutoren: any;
  rstAutorenCount: any;
  dsoAutoren: any;
  rstTextbausteineLaden: any;
  rstTextbausteine: any;
  rstTextbausteineCount: any;

  constructor(private injector: Injector) {
  }

  ngOnInit() {
    this.notificationService = this.injector.get(NotificationService);

    this.configService = this.injector.get(ConfigService);

    this.dialogService = this.injector.get(DialogService);

    this.dialogRef = this.injector.get(DialogRef, null);

    this.locale = this.injector.get(LOCALE_ID);

    this.router = this.injector.get(Router);

    this.cd = this.injector.get(ChangeDetectorRef);

    this._location = this.injector.get(Location);

    this.route = this.injector.get(ActivatedRoute);

    this.httpClient = this.injector.get(HttpClient);

    this.dbHopeKurseTextbausteine = this.injector.get(DbHopeKurseTextbausteineService);
    this.security = this.injector.get(SecurityService);
  }

  ngAfterViewInit() {
    this._subscription = this.route.params.subscribe(parameters => {
      if (this.dialogRef) {
        this.parameters = this.injector.get(DIALOG_PARAMETERS);
      } else {
        this.parameters = parameters;
      }
      this.load();
      this.cd.detectChanges();
    });
  }

  ngOnDestroy() {
    if (this._subscription) {
      this._subscription.unsubscribe();
    }
  }


  load() {
    this.gridAutoren.load();
  }

  gridAutorenLoadData(event: any) {
    this.dbHopeKurseTextbausteine.getIbsiTextbausteineAutorens(`${event.filter}`, event.top, event.skip, `${event.orderby || 'Name'}`, event.top != null && event.skip != null, null, null, null)
    .subscribe((result: any) => {
      this.rstAutoren = result.value;

      this.rstAutorenCount = event.top != null && event.skip != null ? result['@odata.count'] : result.value.length;

      if (this.rstAutoren.find(p => p.AutorNr == this.letzteAutorNr) != null) {
    // letzteAutorNr wurde in rstAutoren gefunden
    this.gridAutoren.onSelect(this.rstAutoren.find(p => p.AutorNr == this.letzteAutorNr))
} else {
    // letzteAutorNr wurde in rstAutoren NICHT gefunden
    this.letzteAutorNr = null;
    this.gridAutoren.onSelect(this.rstAutoren[0]);
}
    }, (result: any) => {
      this.notificationService.notify({ severity: "error", summary: ``, detail: `Autoren konnten nicht geladen werden!` });
    });
  }

  gridAutorenRowDoubleClick(event: any) {
    this.letzteAutorNr = this.dsoAutoren.AutorNr;

    this.dialogService.open(AutorenBearbeitenComponent, { parameters: {AutorNr: this.dsoAutoren.AutorNr}, title: `Bearbeiten Autor` });
  }

  gridAutorenRowSelect(event: any) {
    this.dsoAutoren = event;

    this.rstTextbausteineLaden = true;

    this.dbHopeKurseTextbausteine.getIbsiTextbausteines(`AutorNr eq ${event.AutorNr}`, event.top, event.skip, `IbsiKurse/Titel, TitelTextbaustein`, event.top != null && event.skip != null, `IbsiKurse, IbsiTextbausteineArten`, null, `TextbausteinNr, TitelTextbaustein, UntertitelTextbaustein`)
    .subscribe((result: any) => {
      this.rstTextbausteine = result.value;

      this.rstTextbausteineCount = event.top != null && event.skip != null ? result['@odata.count'] : result.value.length;

      this.rstTextbausteineLaden = false;
    }, (result: any) => {

    });
  }

  buttonNeuClick(event: any) {
    this.letzteAutorNr = this.dsoAutoren.AutorNr;

    this.dialogService.open(AutorenNeuComponent, { parameters: {}, title: `Neuer Autor ` })
        .afterClosed().subscribe(result => {
              if (result != null) {
            this.letzteAutorNr = result.AutorNr;
      }

      if (result != null) {
        this.gridAutoren.load();
      }
    });
  }

  buttonBearbeitenClick(event: any) {
    this.letzteAutorNr = this.dsoAutoren.AutorNr;

    this.dialogService.open(AutorenBearbeitenComponent, { parameters: {AutorNr: this.dsoAutoren.AutorNr}, title: `Bearbeiten Autor` });
  }

  buttonLoeschenClick(event: any) {
    this.letzteAutorNr = null;

    this.dialogService.open(MeldungLoeschenComponent, { parameters: {strMeldung: "Soll der Autor '" + this.dsoAutoren.Name + "' gelöscht werden?"}, title: `Löschen Autor` })
        .afterClosed().subscribe(result => {
              if (result == 'Löschen') {
              this.dbHopeKurseTextbausteine.deleteIbsiTextbausteineAutoren(this.dsoAutoren.AutorNr)
        .subscribe((result: any) => {
              this.notificationService.notify({ severity: "success", summary: ``, detail: `Autor gelöscht` });
        }, (result: any) => {
              this.notificationService.notify({ severity: "error", summary: ``, detail: `Autor konnte nicht gelöscht werden!` });
        });
      }
    });
  }
}
